"use client";

import { useState, useEffect, use } from "react";
import { Loader2, Printer, ArrowLeft } from "lucide-react";
import Link from "next/link";
import axios from "axios";

export default function InvoicePage(props: { params: Promise<{ id: string }> }) {
    const params = use(props.params);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const [bill, setBill] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchBill();
    }, [params.id]);

    const fetchBill = async () => {
        try {
            const res = await axios.get(`/api/bills/${params.id}`);
            setBill(res.data);
        } catch (error) {
            console.error("Failed to fetch bill", error);
        } finally {
            setLoading(false);
        }
    };

    if (loading) return <div className="p-12 text-center flex justify-center"><Loader2 className="animate-spin" /></div>;
    if (!bill) return <div className="p-12 text-center text-red-500">Invoice not found</div>;

    const invoiceDate = new Date(bill.generatedAt).toLocaleDateString();

    return (
        <div className="max-w-3xl mx-auto print:max-w-none print:w-full">
            <div className="print:hidden flex justify-between items-center mb-8">
                <Link href="/bills" className="flex items-center gap-2 text-gray-500 hover:text-gray-900">
                    <ArrowLeft className="w-5 h-5" /> Back
                </Link>
                <button
                    onClick={() => window.print()}
                    className="bg-gray-900 text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-black transition-colors"
                >
                    <Printer className="w-4 h-4" /> Print Invoice
                </button>
            </div>

            <div className="bg-white p-12 rounded-xl shadow-lg border border-gray-100 print:shadow-none print:border-none print:p-8">
                <div className="flex justify-between items-start mb-12 border-b border-gray-100 pb-8">
                    <div>
                        <h1 className="text-4xl font-bold text-ruby-700 mb-2">INVOICE</h1>
                        <p className="text-gray-500 text-sm">#{bill.id.slice(-6).toUpperCase()}</p>
                    </div>
                    <div className="text-right">
                        <h2 className="font-bold text-gray-900 text-xl">{bill.warehouse?.name || "WMS Corp"}</h2>
                        <p className="text-gray-500 text-sm">{bill.warehouse?.location || "Warehouse Location"}</p>
                    </div>
                </div>

                <div className="grid grid-cols-2 gap-8 mb-12">
                    <div>
                        <p className="text-xs uppercase font-bold text-gray-400 tracking-wider mb-2">Billed To</p>
                        <h3 className="font-bold text-gray-900 text-lg">{bill.trip?.vehicle?.driverName}</h3>
                        <p className="text-gray-500">{bill.trip?.vehicle?.number}</p>
                    </div>
                    <div className="text-right">
                        <div className="mb-2">
                            <p className="text-xs uppercase font-bold text-gray-400 tracking-wider">Date</p>
                            <p className="font-bold text-gray-900">{invoiceDate}</p>
                        </div>
                        <div>
                            <p className="text-xs uppercase font-bold text-gray-400 tracking-wider">Generated By</p>
                            <p className="font-medium text-gray-900">{bill.generator?.name || "Admin"}</p>
                        </div>
                    </div>
                </div>

                <table className="w-full mb-12">
                    <thead className="bg-gray-50 text-gray-500 font-medium text-sm">
                        <tr>
                            <th className="px-4 py-3 text-left">Item Description</th>
                            <th className="px-4 py-3 text-right">Sold Qty</th>
                            <th className="px-4 py-3 text-right">Price</th>
                            <th className="px-4 py-3 text-right">Total</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
                        {Array.isArray(bill.trip?.loadedItems) && bill.trip.loadedItems.map((item: any, idx: number) => {
                            const sold = item.qtyLoaded - (item.qtyReturned || 0);
                            if (sold <= 0) return null;
                            return (
                                <tr key={idx}>
                                    <td className="px-4 py-3 font-medium text-gray-900">
                                        {item.productName}
                                        <span className="text-gray-400 font-normal text-xs block">{item.productSku}</span>
                                    </td>
                                    <td className="px-4 py-3 text-right text-gray-600">{sold}</td>
                                    <td className="px-4 py-3 text-right text-gray-600">₹{item.productPrice}</td>
                                    <td className="px-4 py-3 text-right font-medium text-gray-900">₹{sold * item.productPrice}</td>
                                </tr>
                            );
                        })}
                    </tbody>
                </table>

                <div className="flex justify-end border-t border-gray-100 pt-8">
                    <div className="w-64">
                        <div className="flex justify-between items-center mb-4">
                            <span className="font-medium text-gray-500">Subtotal</span>
                            <span className="font-bold text-gray-900">₹{bill.totalAmount.toLocaleString()}</span>
                        </div>
                        <div className="flex justify-between items-center text-xl pt-4 border-t border-gray-200">
                            <span className="font-bold text-ruby-700">Total</span>
                            <span className="font-bold text-ruby-700">₹{bill.totalAmount.toLocaleString()}</span>
                        </div>
                    </div>
                </div>

                <div className="mt-12 text-center text-gray-400 text-sm print:fixed print:bottom-8 print:w-full">
                    Thank you for your business.
                </div>
            </div>
        </div>
    );
}
