import dbConnect from "./mongodb";
import * as XLSX from "xlsx";
import * as fs from "fs";
import * as path from "path";
import { formatIST } from "./dateUtils";

export async function generateExcelWorkbook(): Promise<XLSX.WorkBook> {
    try {
        const conn = await dbConnect();
        const db = conn.connection.db;
        if (!db) throw new Error("DB not initialized");

        // 1. Fetch Warehouses and map for quick lookup
        const warehouses = await db.collection("Warehouse").find().toArray();
        const warehouseMap = new Map(warehouses.map(w => [w._id.toString(), w.name]));

        // 2. Fetch Users and map
        const users = await db.collection("User").find().toArray();
        const userMap = new Map(users.map(u => [u._id.toString(), u.name || u.email]));

        // 3. Fetch Products
        const products = await db.collection("Product").find().toArray();
        const productMap = new Map(products.map(p => [p._id.toString(), p]));
        const productRows = products.map(p => ({
            "Product ID": p._id.toString(),
            "Name": p.name || "",
            "SKU": p.sku || "",
            "Flavour": p.flavour || "",
            "Pack": p.pack || "",
            "Quantity": p.quantity ?? 0,
            "MRP (Base Price)": p.price ?? 0,
            "Invoice Cost": p.invoiceCost ?? 0,
            "Sale Price": p.salePrice ?? 0,
            "Location": p.location || "",
            "Warehouse": warehouseMap.get(p.warehouseId?.toString()) || "Unknown",
            "Created At": p.createdAt ? formatIST(p.createdAt) : "",
            "Updated At": p.updatedAt ? formatIST(p.updatedAt) : ""
        }));

        // 4. Fetch Vehicles
        const vehicles = await db.collection("Vehicle").find().toArray();
        const vehicleMap = new Map(vehicles.map(v => [v._id.toString(), v]));
        const vehicleRows = vehicles.map(v => ({
            "Vehicle ID": v._id.toString(),
            "Vehicle Number": v.number || "",
            "Driver Name": v.driverName || "",
            "Status": v.status || "",
            "Warehouse": warehouseMap.get(v.warehouseId?.toString()) || "Unknown",
            "Created At": v.createdAt ? formatIST(v.createdAt) : "",
            "Updated At": v.updatedAt ? formatIST(v.updatedAt) : ""
        }));

        // 5. Fetch Trips
        const trips = await db.collection("Trip").find().toArray();
        const tripRows = trips.map(t => {
            const vehicle = vehicleMap.get(t.vehicleId?.toString());
            
            // Format items loaded
            const itemsStr = (t.loadedItems || []).map((item: any) => {
                const prod = productMap.get(item.productId?.toString());
                const name = prod ? prod.name : "Unknown Product";
                return `${name} (Loaded: ${item.qtyLoaded || 0}, Returned: ${item.qtyReturned || 0})`;
            }).join("; ");

            return {
                "Trip ID": t._id.toString(),
                "Warehouse": warehouseMap.get(t.warehouseId?.toString()) || "Unknown",
                "Vehicle Number": vehicle ? vehicle.number : "Unknown",
                "Driver Name": vehicle ? vehicle.driverName : "Unknown",
                "Status": t.status || "",
                "Loaded Items Details": itemsStr,
                "Start Time": t.startTime ? formatIST(t.startTime) : (t.createdAt ? formatIST(t.createdAt) : ""),
                "End Time": t.endTime ? formatIST(t.endTime) : "",
                "Verified By": userMap.get(t.verifiedBy?.toString()) || "",
                "Created At": t.createdAt ? formatIST(t.createdAt) : "",
                "Updated At": t.updatedAt ? formatIST(t.updatedAt) : ""
            };
        });

        // 6. Fetch Bills
        const bills = await db.collection("Bill").find().toArray();
        const billRows = bills.map(b => {
            const trip = trips.find(t => t._id.toString() === b.tripId?.toString());
            const vehicle = trip ? vehicleMap.get(trip.vehicleId?.toString()) : null;
            return {
                "Bill ID": b._id.toString(),
                "Trip ID": b.tripId?.toString() || "",
                "Vehicle Number": vehicle ? vehicle.number : "Unknown",
                "Driver Name": vehicle ? vehicle.driverName : "Unknown",
                "Total Amount (INR)": b.totalAmount ?? 0,
                "Total Profit (INR)": b.totalProfit ?? 0,
                "Generated By": userMap.get(b.generatedBy?.toString()) || "Unknown",
                "Generated At": b.generatedAt ? formatIST(b.generatedAt) : "",
                "Created At": b.createdAt ? formatIST(b.createdAt) : ""
            };
        });

        // 7. Fetch Daily Pricing
        const dailyPricing = await db.collection("DailyPricing").find().toArray();
        const dailyPricingRows = dailyPricing.map(dp => {
            const prod = productMap.get(dp.productId?.toString());
            return {
                "Product Name": prod ? prod.name : "Unknown",
                "SKU": prod ? prod.sku : "Unknown",
                "Date": dp.date || "",
                "Daily Price (INR)": dp.price ?? 0,
                "Warehouse": warehouseMap.get(dp.warehouseId?.toString()) || "Unknown",
                "Updated At": dp.updatedAt ? formatIST(dp.updatedAt) : ""
            };
        });

        // Create Workbook
        const wb = XLSX.utils.book_new();

        // Sheet Definitions
        const sheetsData = [
            { name: "Products & Stock", data: productRows },
            { name: "Vehicles", data: vehicleRows },
            { name: "Trips & Movements", data: tripRows },
            { name: "Bills & Sales", data: billRows },
            { name: "Daily Pricing Overrides", data: dailyPricingRows }
        ];

        for (const sheet of sheetsData) {
            const ws = XLSX.utils.json_to_sheet(sheet.data.length > 0 ? sheet.data : [{}]);
            
            // Format column widths nicely
            if (sheet.data.length > 0) {
                const max_widths = Object.keys(sheet.data[0]).map(key => {
                    let maxLen = key.length;
                    for (const r of sheet.data) {
                        const val = (r as any)[key];
                        const len = val ? String(val).length : 0;
                        if (len > maxLen) maxLen = len;
                    }
                    return { wch: Math.min(maxLen + 3, 50) };
                });
                ws['!cols'] = max_widths;
            }
            
            XLSX.utils.book_append_sheet(wb, ws, sheet.name);
        }

        return wb;
    } catch (error) {
        console.error("Error in generateExcelWorkbook:", error);
        throw error;
    }
}

export async function triggerExcelSync() {
    try {
        const isDev = process.env.NODE_ENV === "development";
        if (isDev) {
            const wb = await generateExcelWorkbook();
            const publicDir = path.join(process.cwd(), "public");
            if (!fs.existsSync(publicDir)) {
                fs.mkdirSync(publicDir, { recursive: true });
            }
            const publicFilePath = path.join(publicDir, "warehouse_data.xlsx");
            XLSX.writeFile(wb, publicFilePath);
            console.log("Excel sync succeeded (dev write to disk) at:", formatIST(new Date()));
        }
    } catch (error) {
        console.error("Error in triggerExcelSync:", error);
    }
}
